# https://docs.traefik.io/configuration/backends/file/#reference
[backends]
  [backends.rundeck]
    [backends.rundeck.servers.server1]
      url = "http://rundeck:4440"
    [backends.rundeck.healthCheck]
      path = "/api/1/system/info"
      port = 4440
      interval = "5s"

[frontends]
  [frontends.rundeck]
    backend = "rundeck"
    # that sets our X-Forward-Host headers
    passHostHeader=true        
    [frontends.rundeck.routes.test_1]
      rule = "Host:rundeck.lan"
